### ISSUE TITLE
Reservation costs

### ISSUE THREAD

**Issue by otbrown** [ARCHER2-HPC/archer2-website#1378]
Jobs that breach all standard QoS limits will typically be required to run in a reservation, which are charged at 1.5x. It would be nice if the CU calculator noticed this. 

At first glance the logic for applying the reservation modifier would be:
```
if ( (time > 24 && nnode > 64) || (time > 12 && nnode > 1024) )  
```
as such a job would break both the `long` and `largescale` QoS. It would probably be sensible to also flag up to the user that this is happening, and that would need to contact the service desk to arrange a reservation.

**Comment by aturner-epcc** [comment]
@xguo-epcc I have assigned this to you but we discussed in the web/docs meetings and are not convinced this is a good idea as we want to explicitly pick this up in a TA review but wanted your opinion.
