### ISSUE TITLE
Enhance Partners page

### ISSUE THREAD

**Issue by aturner-epcc** [ARCHER2-HPC/archer2-website#6]
The ARCHER Partners page (https://www.archer2.ac.uk/about/partners.html) should have:

   - The logo for each partner
   - A short paragraph describing them and what they bring to the ARCHER2 service
   - A link to their website

**Comment by aturner-epcc** [comment]
It would also be good to have a section introducing the team behind ARCHER2 with images and short bios

**Comment by aturner-epcc** [comment]
Potentially also add blogs introducing each of the teams (e.g. USL, CSE, Cray, UKRI)

**Comment by aturner-epcc** [comment]
For bio: picture that indicates your character rather than standard corporate photos

**Comment by clairbarrass** [comment]
Partner logos and links to their websites, along with brief partner blurb added
#1005
22nd Feb
