### ISSUE TITLE
Acknowledging ARCHER2 - text for users to cite in publications

### ISSUE THREAD

**Issue by clairbarrass** [ARCHER2-HPC/archer2-website#776]
We need a bit like
https://www.archer.ac.uk/documentation/user-guide/introduction.php#acknowledge
for ARCHER2

There is an eCSE specific acknowledge text
https://www.archer2.ac.uk/ecse/calls/#acknowledging-archer2

but I can't find anything for more general access routes.

**Comment by clairbarrass** [comment]
I am happy to add some text but would like guidance on the exact wording.

**Comment by aturner-epcc** [comment]
This has been done
